---
title: "lgbtq_movies"
author: "Vandrade"
date: "2024-06-25"
output: html_document
---

```{r, warning= FALSE}

library(tidyverse)
library(tidytuesdayR)
library(ggforce)
library(ggtext)

tuesdata <- tt_load('2024-06-25')

df <- tuesdata$lgbtq_movies

```

c('#ff0000','#ff7400','#fff400', '#00ff04', '#00ecff')

```{r}

pride <- df |> 
  arrange(release_date) |> 
  mutate(release_year = lubridate::year(release_date),
         id = as.factor(id))

```

```{r}

pride |> 
  filter(popularity > 1, vote_count > 200) |> 
  group_by(release_year) |> 
  summarise(n = n(),
            adult = sum(adult == TRUE),
            videos = sum(video == TRUE),
            vote_average = mean(vote_average)) |>
  mutate(rep_adult = adult/n) |> 
  arrange(desc(release_year)) |> 
  ggplot(aes(x = release_year, y = n, color = NULL, fill = release_year)) +
  geom_col() + 
  theme_minimal() +
  labs(x = 'Ano de Lançamento',
       y = NULL) + 
  scale_fill_gradientn(colours = c('#00ecff','#00ff04','#fff400', '#ff7400', '#ff0000')) + 
  xlim(1940,2022)


```
```{r}
pride |> 
  arrange(release_year)

```

```{r}

pride |> 
  mutate(title = fct_reorder(title, popularity)) |> 
  filter(popularity > 35) |> 
  ggplot(aes(x = title, y = popularity, color = NULL, fill = popularity)) +
  geom_col() +
  coord_flip() +
  scale_fill_gradientn(colours = c('#00ecff','#00ff04','#fff400', '#ff7400', '#ff0000')) + 
  theme_minimal() + 
  labs(y = 'Popularity',
       x = NULL)

pride |> 
  mutate(title = fct_reorder(title, popularity)) |> 
  filter(popularity > 35) |> 
  ggplot(aes(x = title, y = log(popularity), color = NULL, fill = log(popularity))) +
  geom_col() +
  coord_flip() +
  scale_fill_gradientn(colours = c('#00ecff','#00ff04','#fff400', '#ff7400', '#ff0000')) +
  theme_minimal() + 
  labs(y = 'Popularity',
       x = NULL)  

```
```{r}

pride |> 
  ggplot(aes(x = log(popularity))) +
  geom_boxplot() 


```

```{r plot, fig.width = 10, fig.height = 9.2}

pride |> 
  filter(popularity > 1,
         vote_count > 500) |> 
  mutate(id = fct_reorder(id, release_year)) |> 
  ggplot(aes(x = id, y = vote_average, color = release_year, fill = release_year)) +
  geom_link(aes(x = id, xend = id, y = 0 ,yend = vote_average, 
                           alpha = vote_average), n = 300, size = 1) +
  coord_polar(theta = "y", start = 3*pi/2, clip = "off") + 
  geom_point(aes(y = 0), shape = 17, size = .3) + 
  geom_point(aes(y = vote_average + .04, size = log(popularity))) + 
  geom_text(aes(y = 0, label = "|"), family = "Changa", fontface = "bold", size = 4, vjust = 1) + 
  ylim(0, 20)




```


```{r}

pride |>  
  filter(popularity > 10, vote_count > 250) |> 
  arrange(desc(popularity))
    
             
pride |> 
  filter(popularity > 1, vote_count > 200) |> 
  filter(popularity > 10,
         release_year > 1970) |> 
  group_by(release_year) |> 
  summarise(n = n(),
            adult = sum(adult == TRUE),
            videos = sum(video == TRUE),
            vote_average = mean(vote_average)) |>
  mutate(rep_adult = adult/n) |> 
  arrange(desc(release_year)) |> 
  ggplot(aes(x = release_year, y = n, color = NULL, fill = release_year)) +
  geom_col() + 
  theme_minimal() +
  labs(x = 'Ano de Lançamento',
       y = NULL) + 
  scale_fill_gradientn(colours = c('#00ecff','#00ff04','#fff400', '#ff7400', '#ff0000')) + 
  xlim(1970, 2022)

```

```{r}
df_missions <-
  df_astro %>% 
  group_by(name) %>% 
  summarize(
    hours = sum(hours_mission),
    year = min(year_of_mission),
    max_year = max(year_of_mission)
  ) %>% 
  ungroup() %>% 
  mutate(year = -year) %>% 
  arrange(year) %>% 
  mutate(id = row_number())

df_labs <-
  df_missions %>% 
  filter(year %in% c(-1961, -197:-201*10, -2019)) %>% 
  group_by(year) %>% 
  filter(id == min(id)) 

df_labs <- pride |> 
  filter(vote_count > 200,
         release_year %in% c(1943, 1960, 2000, 2010, 2020)) |> 
  group_by(release_year) |> 
  summarise(release_year = min(release_year),
            id = first(id))


pride |> 
  filter(vote_count > 200) |> 
  arrange(release_date)
```



```{r plot, fig.width = 25, fig.height = 23.63}



pride_graf <- pride |> 
  filter(vote_count > 200) |> 
  mutate(id = fct_reorder(id, desc(release_date)),
         release_id = row_number(id))


df_labs <- pride_graf |> 
  filter(release_year %in% c(1943, 1990, 2000, 2010, 2015, 2018, 2021)) |> 
  group_by(release_year) |> 
  summarise(release_year = min(release_year),
            id = first(id),
            release_id = first(release_id))


pride_graf|>
  ggplot(aes(x = release_id, y = log(popularity), color = -release_year, fill = -release_year)) +
  geom_link(aes(x = release_id, xend = release_id, y = 0 , yend = log(popularity), 
                           alpha = log(popularity)), n = 300, size = 1) +
  coord_polar(theta = "y", start = 3*pi/2, clip = "off") + 
  geom_point(aes(y = 0), shape = 17, size = 2) + 
  geom_point(aes(y = log(popularity), size = vote_average)) + 
  geom_text(data = df_labs, aes(y = 0, label = "|"), family = "Changa", fontface = "bold", size = 5, vjust = 1) + 
  scale_color_gradientn(colours = c('#00ecff','#00ff04','#fff400', '#ff7400', '#ff0000')) +
  geom_richtext(data = df_labs, aes(y = 0, label = release_year), size = 11, family = "Oswald", fontface = "bold",
                fill = NA, label.color = NA, vjust = 1.5) + 
  ylim(0, 6.5) + 
  xlim(-30, 239) + 
  labs(x = NULL,
       y = NULL) + 
  theme(legend.position = 'none') + 
    geom_textbox(data = tibble(release_id = 239, popularity = 6, label = "<b style='font-size:38pt;'>Most Popular LGBTQ+ Movies</b><br><br>", release_year = 1943), aes(x = release_id, y = popularity, label = label), nherit.aes = F,
      size = 7.3,
      family = "Oswald",
      color = "black",
      lineheight = 1.3,
      width = unit(6.2, "inch"),
      hjust = .2,
      vjust = -.8,
      fill = NA,
      box.colour = NA) + 
  annotate("text", x = 239, y = 4.7, label = "Visualization by Vicente Andrade • Data by TidyRainbow • Curated by Cara Cuiule",
      family = "Oswald",
      size = 5.6, 
      color = "grey50",
      hjust = .65)


```






```{r plot, fig.width = 25, fig.height = 23.63}

pride_graf|>
  ggplot(aes(x = release_id, y = log(popularity) - 2, color = -release_year, fill = -release_year)) +
  geom_link(aes(x = release_id, xend = release_id, y = 0 , yend = log(popularity)- 2, 
                           alpha = log(popularity)), n = 300, size = 1) +
  coord_polar(theta = "y", start = 3*pi/2, clip = "off") + 
  geom_point(aes(y = 0), shape = 17, size = .3) + 
  geom_point(aes(y = log(popularity)- 2, size = vote_average)) + 
  geom_text(data = df_labs, aes(y = 0, label = "|"), family = "Changa", fontface = "bold", size = 4, vjust = 1) + 
  scale_color_gradientn(colours = c('#00ecff','#00ff04','#fff400', '#ff7400', '#ff0000')) +
  geom_richtext(data = df_labs, aes(y = 0, label = release_year), size = 7, family = "Oswald", fontface = "bold",
                fill = NA, label.color = NA, vjust = 1) + 
  ylim(0, 6.5) + 
  xlim(-30, 239) + 
  labs(x = NULL,
       y = NULL) + 
  theme(legend.position = 'none')

```

```{r plot, fig.width = 25, fig.height = 23.63}

pride_graf|>
  ggplot(aes(x = release_id, y = popularity - 3 , color = -release_year, fill = -release_year)) +
  geom_link(aes(x = release_id, xend = release_id, y = 0 , yend = popularity - 3, 
                           alpha = popularity), n = 300, size = 1) +
  coord_polar(theta = "y", start = 3*pi/2, clip = "off") + 
  geom_point(aes(y = 0), shape = 17, size = .3) + 
  geom_point(aes(y = popularity - 3, size = vote_average)) + 
  geom_text(data = df_labs, aes(y = 0, label = "|"), family = "Changa", fontface = "bold", size = 4, vjust = 1) + 
  scale_color_gradientn(colours = c('#00ecff','#00ff04','#fff400', '#ff7400', '#ff0000')) +
  geom_richtext(data = df_labs, aes(y = 0, label = release_year), size = 7, family = "Oswald", fontface = "bold",
                fill = NA, label.color = NA, vjust = .85) + 
  xlim(-30, 239) + 
  ylim(0, 100) + 
  labs(x = NULL,
       y = NULL) + 
  theme(legend.position = 'none')



```


geom_richtext(
      data = df_labs,
      aes(y = 0, label = glue::glue("<br>{abs(year)}")),
      size = 5.5,
      family = "Oswald",
      fontface = "bold",
      fill = NA,
      label.color = NA,
      vjust = .85
    )




```{r}

pride |> 
  filter(popularity > 1, vote_count > 200) |> 
  mutate(id = fct_reorder(id, desc(release_date))) |> 
  ggplot(aes(x = id, y = log(popularity) - 2, color = -release_year, fill = -release_year)) +
  geom_link(aes(x = id, xend = id, y = 0 ,yend = log(popularity) - 2, 
                           alpha = log(popularity) - 2), n = 300, size = 1) +
  coord_polar(theta = "y", start = 3*pi/2, clip = "off") + 
  geom_point(aes(y = 0), shape = 17, size = .3) + 
  geom_point(aes(y = log(popularity) - 2, size = vote_average)) + 
  geom_text(aes(y = 0, label = "|"), family = "Changa", fontface = "bold", size = 4, vjust = 1) + 
  scale_color_gradientn(colours = c('#00ecff','#00ff04','#fff400', '#ff7400', '#ff0000')) +
  geom_richtext(aes(y = 0, label = release_year), size = 5.5, family = "Oswald", fontface = "bold",
                fill = NA, label.color = NA, vjust = .85) + 
  ylim(0, 6)


```






























